export enum CampaignType {
  MARKET_MAKING = 'MARKET_MAKING',
  COMPETITIVE_MARKET_MAKING = 'COMPETITIVE_MARKET_MAKING',
  HOLDING = 'HOLDING',
  THRESHOLD = 'THRESHOLD',
}

export const ALLOWED_AUTOJOIN_CAMPAIGN_TYPES = [
  CampaignType.MARKET_MAKING,
  CampaignType.HOLDING,
] as const;
