version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_PORT=${DB_PORT}
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '${DB_PORT}:${DB_PORT}'
