version: '3.8'
name: hufi-recording-oracle
services:
  postgres:
    container_name: hufi-recording-oracle-db
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '${POSTGRES_PORT}:5432'
