version: '3.8'
name: hufi-recording-oracle
services:
  postgres:
    container_name: hufi-recording-oracle-db
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '${POSTGRES_PORT}:5432'
  minio:
    container_name: hufi-recording-oracle-storage
    image: minio/minio:RELEASE.2022-05-26T05-48-41Z
    ports:
      - 9001:9001
      - 9000:9000
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    entrypoint: 'sh'
    command: -c "mkdir -p /data/recordings && minio server /data --console-address ':9001'"
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 5s
      timeout: 5s
      retries: 3
  minio-mc:
    container_name: hufi-recordings-oracle-storage-mc
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 ${S3_ACCESS_KEY} ${S3_SECRET_KEY};
      /usr/bin/mc mb myminio/recordings;
      /usr/bin/mc anonymous set public myminio/recordings;
      "
