---
# SEV Host Inventory
# Override with: ansible-playbook -i inventory/hosts.yml -e "sev_host=your-host"

all:
  hosts:
    sev_host:
      ansible_host: "{{ sev_host_ip | default('51.68.31.68') }}"
      ansible_user: "{{ sev_host_user | default('ubuntu') }}"
      ansible_ssh_private_key_file: "{{ sev_host_ssh_key | default(omit) }}"
      ansible_python_interpreter: /usr/bin/python3

  children:
    sev_hosts:
      hosts:
        sev_host:

    # SEV VMs (dynamically added after provisioning)
    sev_vms:
      hosts: {}
