name: Deploy Campaign Launcher UI

on:
  push:
    paths:
      - "campaign-launcher/interface/**"
  pull_request:
    paths:
      - "campaign-launcher/interface/**"

jobs:
  campaign-launcher-ui-testnet:
    name: Deploy Campaign Launcher UI on Testnet
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Trigger deployment
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_CAMPAIGN_LAUNCHER_UI_TESTNET_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_CAMPAGIN_LAUNCHER_UI_TESTNET_API_KEY }}
          wait-for-success: true
  campaign-launcher-ui-mainnet:
    name: Deploy Campaign Launcher UI on Mainnet
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Trigger deployment
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_CAMPAIGN_LAUNCHER_UI_MAINNET_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_CAMPAGIN_LAUNCHER_UI_MAINNET_API_KEY }}
          wait-for-success: true
