name: Deploy Campaign Launcher UI Mainnet

on:
  push:
    branches:
      - main
    paths:
      - "campaign-launcher/interface/**"
  pull_request:
    branches:
      - main
    paths:
      - "campaign-launcher/interface/**"

jobs:
  render-deploy:
    name: Render deploy
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_CAMPAIGN_LAUNCHER_UI_MAINNET_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_CAMPAGIN_LAUNCHER_UI_MAINNET_API_KEY }}
          wait-for-success: true
