name: Reputation Oracle

on:
  push:
    branches:
      - develop
      - main
    paths:
      - "reputation-oracle/**"
  pull_request:
    branches:
      - develop
      - main
    paths:
      - "reputation-oracle/**"

jobs:
  render-deploy-testnet:
    name: Deploy on Testnet
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.base.ref == 'develop' || github.ref == 'refs/heads/develop' }}
    permissions:
      deployments: write
    steps:
      - uses: actions/checkout@v3
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_REPUTATION_ORACLE_TESTNET_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          clear_cache: true
          wait_deploy: true
          github_deployment: true
          deployment_environment: "Reputation Oracle Testnet"
          github_token: ${{ secrets.GITHUB_TOKEN }}
  render-deploy-mainnet:
    name: Deploy on Mainnet
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.base.ref == 'main' || github.ref == 'refs/heads/main' }}
    permissions:
      deployments: write
    steps:
      - uses: actions/checkout@v3
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_REPUTATION_ORACLE_MAINNET_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          clear_cache: true
          wait_deploy: true
          github_deployment: true
          deployment_environment: "Reputation Oracle Mainnet"
          github_token: ${{ secrets.GITHUB_TOKEN }}
